<?php

    //-----------------------------------------------------
    // CONSTANTES PARA ESTABLECER LA CONEXION CON LA DB
    //-----------------------------------------------------
    define( 'HOSTXX', 'bd13.intrared.net:3306' );
    define( 'USUARI', 'satt_faro' );
    define( 'PASSWD', 'sattfaro' );
    define( 'DATABA', 'satt_faro' );
    define( 'CENTRA', 'satt_standa' );
    //-----------------------------------------------------

?>
